---
title: "title"
author: "author"
abstract: "abstract"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
geometry: left=1.7cm, right=1.7cm, top=3cm, bottom=3cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true

---



```{r setup,include=F}

options(digits=3)  #Arrendodamento
options(scipen=999)
ggplot2::theme_set(ggplot2::theme_minimal()) #Tema dos gráficos produzidos no ggplot2
knitr::opts_chunk$set(echo=F,message=F,warning=F,fig.pos = 'H',fig.align = 'center',fig.width=7.8, fig.height=4.85)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette="Set2") #Fixa a scale do fill dos gráficos do ggplot2

```


# Introdução
```{r }
#Aqui vão códigos em R
library(tidyverse)

df = read_csv('https://raw.githubusercontent.com/AlissonRP/MLG-trab/main/Pokemon.csv') |> 
  select(-`Type 2`, `#`, -Name,) |> 
  mutate(Legendary = factor(ifelse(Legendary == F, 0, 1)))
```

# Análise Descritiva

```{r}
#Sim, da pra fazer vários de gráficos nessa seção, porém vamos tentar barras quando for estritamente necessário
# Se aparecer um gráfico de pizza vc é removido desse trabalho
df |> 
  group_by(`Type 1`) |> 
  summarise(HP = mean(HP), n = n())
```


# Análise Preditiva

# Análise Inferencial
```{r crftable}

iris |>  
mypdf1::pdf1_freq.tbl(Species,"seila") |> 
  mypdf1::pdf1_tbl("You can combine this function too!")
    
```
Você faz referência cruzada de tabelas assim: Tabela \@ref(tab:crftable)

```{r crfgraph, fig.cap = "Nome da figura"}
plot(rnorm(500))
```

Você faz referência cruzada de figuras assim: Figura \@ref(fig:crfgraph)


# Bibliography



